version: '3'

services:
  app:
    image: pedrofonseca447/csg6-agendaacademicaintegrada:latest
    container_name: agendaacademicaintegrada
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production